/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import static game.Game.levelNumber;
import javax.swing.JToggleButton;

/**
 * The GUI buttons located at the bottom of the window in game
 * @author Junad
 */
public class ControlPanel extends javax.swing.JPanel {

    /**
     * Creates new form ControlPanel
     */
    
    private Game game;
    
    public ControlPanel(Game game) {
        initComponents();
        this.game = game;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        quitButton = new javax.swing.JButton();
        nextLevelButton = new javax.swing.JButton();
        pauseToggleButton = new javax.swing.JToggleButton();
        restartGameButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));

        quitButton.setText("Quit");
        quitButton.setFocusable(false);
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        nextLevelButton.setText("Next Level");
        nextLevelButton.setFocusable(false);
        nextLevelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextLevelButtonActionPerformed(evt);
            }
        });

        pauseToggleButton.setText("Pause");
        pauseToggleButton.setFocusable(false);
        pauseToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseToggleButtonActionPerformed(evt);
            }
        });

        restartGameButton.setText("Restart Game");
        restartGameButton.setFocusable(false);
        restartGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartGameButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(mainMenuButton)
                .addGap(89, 89, 89)
                .addComponent(restartGameButton)
                .addGap(37, 37, 37)
                .addComponent(pauseToggleButton)
                .addGap(18, 18, 18)
                .addComponent(quitButton)
                .addGap(18, 18, 18)
                .addComponent(nextLevelButton)
                .addGap(344, 344, 344))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(quitButton)
                .addComponent(nextLevelButton)
                .addComponent(pauseToggleButton)
                .addComponent(restartGameButton)
                .addComponent(mainMenuButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        System.out.println("Good bye!");
    }//GEN-LAST:event_quitButtonActionPerformed

    private void nextLevelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextLevelButtonActionPerformed
        // TODO add your handling code here:
        game.goNextLevel();
    }//GEN-LAST:event_nextLevelButtonActionPerformed

    private void pauseToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseToggleButtonActionPerformed
        // TODO add your handling code here:
        JToggleButton btn = (JToggleButton) evt.getSource();
        if (btn.isSelected()){
          game.getWorld().stop();
          game.getMyView().pauseTimer();
          if (levelNumber == 1){
              game.level1Music.pause();
          } else if (levelNumber == 2){
              game.level2Music.pause();
          } else if (levelNumber == 3){
              game.level3Music.pause();
          }
          
        } else {
            game.getWorld().start();
            game.getMyView().unpauseTimer();
            if (levelNumber == 1){
              game.level1Music.resume();
          } else if (levelNumber == 2){
              game.level2Music.resume();
          } else if (levelNumber == 3){
              game.level3Music.resume();
          }
            
        }
        
    }//GEN-LAST:event_pauseToggleButtonActionPerformed

    private void restartGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartGameButtonActionPerformed
        // TODO add your handling code here:
//        game.level1Music.stop();
//        game.level2Music.stop();
//        game.level3Music.stop();
//        levelNumber = 1;
        game.getWorld().stop();
        game.restartGame();
        
    }//GEN-LAST:event_restartGameButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // TODO add your handling code here:
        MainMenu mainmenu = new MainMenu();
        mainmenu.setVisible(true);
        game.level1Music.stop();
        game.level2Music.stop();
        game.level3Music.stop();
        game.getWorld().stop();
    }//GEN-LAST:event_mainMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton nextLevelButton;
    private javax.swing.JToggleButton pauseToggleButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton restartGameButton;
    // End of variables declaration//GEN-END:variables
}
